/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtplayerVideo: typeof import('./src/components/Video/ArtplayerVideo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtons: typeof import('element-plus/es')['ElButtons']
    ElButtonss: typeof import('element-plus/es')['ElButtonss']
    ElButtonsss: typeof import('element-plus/es')['ElButtonsss']
    ElColorPickerPanel: typeof import('element-plus/es')['ElColorPickerPanel']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Video: typeof import('./src/components/Video/index.vue')['default']
    Video2: typeof import('./src/components/Video/Video2.vue')['default']
  }
}
