server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # 不带斜杠自动补斜杠
    location ^~ /vue-zero-app {
        return 301 /vue-zero-app/;
    }

    # 匹配二级目录
    location /vue-zero-app/ {
        try_files $uri $uri/ @spa_fallback;
    }

    # 单独兜底，不会再次匹配 /vue-zero-app/
    location @spa_fallback {
        rewrite ^ /vue-zero-app/index.html break;
    }

    # 静态资源缓存
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}